export  class Nurse{
    taille!: number;
    poids!: number; 
    imc!: number;
    allergie!:string;
    température!: number;
    systole!: number;
    dyastole!: number;
    poul!: number;
    couleur!: number;
    cou!: number;
    rythme!: number;
    saturation!: number;
    respiration!: number;
    glycemie!: number;
    sanguin!: string;
    habitudes!: string;
    status!: string;
    poidN!: number;
    cranien!: number;
    poignet!: number;
    poitrine!: number;
    brachiale!: number;
    hanche!: number;
    allergieq!: string;
    description!: number;
    severité!: number;
    reaction!: number;
    tabac!: number;
    alcool!: number;
    histoire!: number;
    bouteilles!: number;
    cigarettes!: number;
    chirurgie!: number;
    medicament !: number;
    observations!: number;
    douleur!: string;
    note!:string;
}