apiVersion: apps/v1 #for version befor 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mvc-deployment
spec:
  selector:
    matchLabels:
      app: mvc
  replicas: 1 # tells deployment to rin 2 pots matching the template
  template:
    metadata:
      labels:
        app: mvc
    spec:
      conatainers:
      - name: mvc
        image: houssendocker/products-store-avc:3.0-prometheus # imageTag
        ports:
        - containerPort: 80
        ressources:
          limits:
            cpu: "1"
            meùory: "200Mi"
          requests:
            cpu: '0.1'
            memory: "100Mi"
        env:
          - name: connectionStrings_productsContext
            valueForm:
              secretKeyRef:
                name: mssql-secret
                key: db-connection-string-secret
 #              configMapKeyRef:
 #               name: mssql-connection-configmap
 #               key: db-connection-string
 ---
 king: service
 apiVersion: v1
 metadata:
  name: mvc-service
 spec:
  selector:
    app: mvc
  port: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer


